apiVersion: skaffold/v2beta12
kind: Config
deploy:
  kubectl:
    manifests:
      - ./k8s/*
      
build:
  # don't push to dockerhub
  local:
    push: false
  # images that skaffold will build, and will manage any containers built from this image.
  artifacts:
    - image: lauferdaniel/auth-server
      context: auth-server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "*.js" # anytime a js file is updated, move it to the container!
            dest: . # where the files should be synced to inside the container. note: If the destination is a relative path, an absolute path will be inferred by prepending the path with the container’s WORKDIR. So in this case it will sync files with the /app directory in this container.
    - image: lauferdaniel/rest-api-server
      context: rest-api-server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "*.js" # anytime a js file is updated, move it to the container!
            dest: . # where the files should be synced to inside the container. note: If the destination is a relative path, an absolute path will be inferred by prepending the path with the container’s WORKDIR. So in this case it will sync files with the /app directory in this container.
    - image: lauferdaniel/front-end-server
      context: front-end
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.js" # anytime a js file is updated, move it to the container!
            dest: .
          - src: "src/**/*.css"
            dest: .
          - src: "src/**/*.html"
            dest: .

  





