
// /login and /register
{
    "username": "daniel",
    "password": "daniel"
}


// /flashcard_collections
{
    "title": "English Word Definitions",
    "flashcards": [
        {
            "front_text": "Formidable",
            "back_text": "inspiring fear or respect through being impressively large, powerful, intense, or capable."
        },
        {
            "front_text": "Palpable",
            "back_text": "(of a feeling or atmosphere) so intense as to seem almost tangible"
        }
    ]
}


