apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
spec: 
  # number of pods for this deployment to manage
  replicas: 1 
  # select all pods with the name auth-server 
  selector:
    matchLabels:
      component: api-gateway 

  template: 
    metadata:
      labels:
        component: api-gateway # label for each pod that is created

    # customize behaviour of each pod that is created
    spec:
      containers:
        - name: api-gateway # name for a container inside this pod
          image: lauferdaniel/flashcard-app-api-gateway
          ports:
            - containerPort: 5000 # exposing port 5000 on container inside pod
          env:
            - name: AUTH_SERVER_IP
              value: auth-server-cluster-ip-service
            - name: REST_API_SERVER_IP
              value: rest-api-server-cluster-ip-service
            - name: AWS_BUCKET_REGION
              valueFrom:
                secretKeyRef:
                  name: aws-user-credentials
                  key: AWS_BUCKET_REGION
            - name: AWS_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: aws-user-credentials
                  key: AWS_BUCKET_NAME
            - name: ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-user-credentials
                  key: ACCESS_KEY
            - name: SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-user-credentials
                  key: SECRET_ACCESS_KEY
              

