apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server-deployment
spec: 
  # number of pods for this deployment to manage
  replicas: 1 
  # select all pods with the name auth-server 
  selector:
    matchLabels:
      component: auth-server 

  template: 
    metadata:
      labels:
        component: auth-server # label for each pod that is created

    # customize behaviour of each pod that is created
    spec:
      containers:
        - name: auth-server # name for a container inside this pod
          image: lauferdaniel/flashcard-app-auth-server
          ports:
            - containerPort: 5000 # exposing port 5000 on container inside pod
          env:
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: PG_USER
            - name: PG_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: PG_HOST
            - name: PG_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: PG_DB
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: PG_PASSWORD
            - name: PG_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: PG_PORT
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET_KEY
              

