apiVersion: apps/v1
kind: Deployment
metadata: 
  name: front-end-server-deployment
# configuration for how this deployment should behave
spec:
  replicas: 1
  selector:
    matchLabels:
      component: front-end 
  template:
    metadata:
      labels:
        component: front-end
    # customize behaviour of each pod that is created
    spec: 
      containers:
        - name: client
          image: lauferdaniel/flashcard-app-front-end
          ports:
            - containerPort: 3000 # expose port 3000 
          env:
            - name: REACT_APP_API_GATEWAY_IP
              value: api-gateway-cluster-ip-service
            - name : REACT_APP_waddup
              value: "daniel"








