apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  accessModes:
    - ReadWriteOnce # ReadWriteOnce -- the volume can be mounted as read-write by a single node
  resources:
    requests:
      storage: 2Gi